version: "3"

services:
    db_server1:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sample
    
    db_server2:
        image: mysql:5.7
        ports: 
            - "3307:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sample